name: Lighthouse CI
on:
  pull_request:
    branches: [main]
jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm ci
      - run: npm run build
      - run: npm run preview & npx wait-on http://localhost:4321
      - name: Lighthouse
        run: npx lighthouse http://localhost:4321 --quiet --chrome-flags="--headless=new" --only-categories=performance,accessibility,seo,best-practices --output html --output-path reports/lh.html --budgets-path=./lighthouse-budgets.json
      - uses: actions/upload-artifact@v4
        with: { name: lighthouse-report, path: reports/lh.html }
